language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
   - phpunit --coverage-clover=coverage.clover --configuration ./phpunit.xml.dist ./tests